# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/ford/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/ford/proprietary/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
    vendor/amazon/ford/proprietary/lib/hw/audio.primary.mt8127.so:system/lib/hw/audio.primary.mt8127.so \
    vendor/amazon/ford/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/amazon/ford/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/amazon/ford/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/amazon/ford/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/amazon/ford/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/amazon/ford/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/amazon/ford/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/amazon/ford/proprietary/lib/libbessound_mtk.so:system/lib/libbessound_mtk.so \
    vendor/amazon/ford/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/amazon/ford/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/amazon/ford/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/amazon/ford/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/amazon/ford/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/amazon/ford/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/amazon/ford/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/amazon/ford/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/amazon/ford/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/amazon/ford/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/amazon/ford/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/amazon/ford/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/amazon/ford/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/amazon/ford/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/amazon/ford/proprietary/bin/PrintBootInfo:system/bin/PrintBootInfo \
    vendor/amazon/ford/proprietary/lib/hw/camera.mt8127.so:system/lib/hw/camera.mt8127.so \
    vendor/amazon/ford/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/amazon/ford/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/amazon/ford/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/amazon/ford/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/amazon/ford/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/amazon/ford/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/amazon/ford/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/amazon/ford/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/amazon/ford/proprietary/lib/libcamera_client_mtk.so:system/lib/libcamera_client_mtk.so \
    vendor/amazon/ford/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/amazon/ford/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/amazon/ford/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/amazon/ford/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/amazon/ford/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/amazon/ford/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/amazon/ford/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/amazon/ford/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/amazon/ford/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/amazon/ford/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/amazon/ford/proprietary/lib/libGdmaScalerPipe.so:system/lib/libGdmaScalerPipe.so \
    vendor/amazon/ford/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/amazon/ford/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/amazon/ford/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/amazon/ford/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/amazon/ford/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/amazon/ford/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    vendor/amazon/ford/proprietary/lib/libmpo.so:system/lib/libmpo.so \
    vendor/amazon/ford/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/amazon/ford/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/amazon/ford/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/amazon/ford/proprietary/etc/firmware/ROMv2_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_patch_1_0_hdr.bin \
    vendor/amazon/ford/proprietary/etc/firmware/ROMv2_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_patch_1_1_hdr.bin \
    vendor/amazon/ford/proprietary/etc/firmware/WIFI_RAM_CODE_8127:system/etc/firmware/WIFI_RAM_CODE_8127 \
    vendor/amazon/ford/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/amazon/ford/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/amazon/ford/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/amazon/ford/proprietary/bin/pq:system/bin/pq \
    vendor/amazon/ford/proprietary/bin/kisd:system/bin/kisd \
    vendor/amazon/ford/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/amazon/ford/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/amazon/ford/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/amazon/ford/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/amazon/ford/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/amazon/ford/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/amazon/ford/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/amazon/ford/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/amazon/ford/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/amazon/ford/proprietary/lib/hw/gralloc.mt8127.so:system/lib/hw/gralloc.mt8127.so \
    vendor/amazon/ford/proprietary/lib/hw/hwcomposer.mt8127.so:system/lib/hw/hwcomposer.mt8127.so \
    vendor/amazon/ford/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/amazon/ford/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/amazon/ford/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/amazon/ford/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/amazon/ford/proprietary/lib/libmtk_mali_user.so:system/lib/libmtk_mali_user.so \
    vendor/amazon/ford/proprietary/bin/aal:system/bin/aal \
    vendor/amazon/ford/proprietary/lib/libaal_cust.so:system/lib/libaal_cust.so \
    vendor/amazon/ford/proprietary/lib/libaal.so:system/lib/libaal.so \
    vendor/amazon/ford/proprietary/lib/hw/keystore.mt8127.so:system/lib/hw/keystore.mt8127.so \
    vendor/amazon/ford/proprietary/lib/liburee_meta_drmkeyinstall_v2.so:system/lib/liburee_meta_drmkeyinstall_v2.so \
    vendor/amazon/ford/proprietary/lib/lib_uree_mtk_crypto.so:system/lib/lib_uree_mtk_crypto.so \
    vendor/amazon/ford/proprietary/lib/hw/lights.mt8127.so:system/lib/hw/lights.mt8127.so \
    vendor/amazon/ford/proprietary/lib/hw/memtrack.mt8127.so:system/lib/hw/memtrack.mt8127.so \
    vendor/amazon/ford/proprietary/bin/thermal_manager:system/bin/thermal_manager \
    vendor/amazon/ford/proprietary/etc/.tp/.ht120.mtc:system/etc/.tp/.ht120.mtc \
    vendor/amazon/ford/proprietary/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf \
    vendor/amazon/ford/proprietary/etc/.tp/thermal.policy.conf:system/etc/.tp/thermal.policy.conf \
    vendor/amazon/ford/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
    vendor/amazon/ford/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/amazon/ford/proprietary/lib/libdrmplayreadydecryptor.so:system/lib/libdrmplayreadydecryptor.so \
    vendor/amazon/ford/proprietary/lib/libgui_ext.so:system/lib/libgui_ext.so \
    vendor/amazon/ford/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/amazon/ford/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/amazon/ford/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/amazon/ford/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/amazon/ford/proprietary/lib/libmp2dec_sb.ca7.so:system/lib/libmp2dec_sb.ca7.so \
    vendor/amazon/ford/proprietary/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    vendor/amazon/ford/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/amazon/ford/proprietary/lib/libMtkOmxAIVPlayer.so:system/lib/libMtkOmxAIVPlayer.so \
    vendor/amazon/ford/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/amazon/ford/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/amazon/ford/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
    vendor/amazon/ford/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/amazon/ford/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/amazon/ford/proprietary/lib/lib_uree_mtk_video_secure_al.so:system/lib/lib_uree_mtk_video_secure_al.so \
    vendor/amazon/ford/proprietary/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
    vendor/amazon/ford/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/amazon/ford/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/amazon/ford/proprietary/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    vendor/amazon/ford/proprietary/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    vendor/amazon/ford/proprietary/bin/msensord:system/bin/msensord \
    vendor/amazon/ford/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/amazon/ford/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/amazon/ford/proprietary/lib/hw/sensors.mt8127.so:system/lib/hw/sensors.mt8127.so \
    vendor/amazon/ford/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/amazon/ford/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/amazon/ford/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/amazon/ford/proprietary/bin/rpmb_svc:system/bin/rpmb_svc \
    vendor/amazon/ford/proprietary/lib/libtz_uree.so:system/lib/libtz_uree.so \
    vendor/amazon/ford/proprietary/bin/thermald:system/bin/thermald \
    vendor/amazon/ford/proprietary/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    vendor/amazon/ford/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant
